/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wherobots_CDataToJavaCppExample */

#ifndef _Included_com_wherobots_CDataToJavaCppExample
#define _Included_com_wherobots_CDataToJavaCppExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wherobots_CDataToJavaCppExample
 * Method:    FillInt64Array
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_wherobots_CDataToJavaCppExample_FillInt64Array
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
